ARG BASE_DOCKER
# Dockerfile that updates the container with new code.
# SageMaker PyTorch image
FROM ${BASE_DOCKER}

# /opt/ml and all subdirectories are utilized by SageMaker, use the /code subdirectory to store your user code.
COPY . /opt/ml/code/

# RUN pip install -e /opt/ml/code/

# Prevent sagemaker from installing requirements again.
RUN rm -f /opt/ml/code/setup.py
RUN rm -f /opt/ml/code/requirements.txt

ENV NCCL_DEBUG=info

RUN mkdir -p /opt/ml/input/data/training
RUN mkdir -p /opt/ml/model/

RUN cp /data/dpo_rlaif/mistral7bsft0.1/policy.pt /opt/ml/model/
RUN cp /data/dpo_rlaif/mistral7bsft0.1/comparisons_gpt4/temp1.0_vs_chatgpt/annotations.json /opt/ml/input/data/training/

# ENV SAGEMAKER_PROGRAM eval/eval_openlm_new.py
# ENV SAGEMAKER_PROGRAM open_lm/main.py